# Increased memory for Gradle to prevent JVM garbage collector thrashing
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
# Disable performance logging if desired
org.gradle.daemon.performance.disable-logging=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
kotlin.incremental=true

# Standard Android Gradle Plugin settings
android.useAndroidX=true
android.nonTransitiveRClass=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
